spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

redis:
  url: ${REDIS_URL:redis://localhost:6379}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
