spring:
  application:
    name: recommendation-service

  datasource:
    url: jdbc:h2:mem:recodb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    org.apache.kafka: ERROR
    com.contentwise.reco: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}